# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconnection',
            old_name='user_id',
            new_name='user',
        ),
    ]
