# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot_app', '0002_auto_20171201_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('ts', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
                ('bot_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_bot_app.BotConnection')),
            ],
        ),
        migrations.CreateModel(
            name='BotReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bot_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_bot_app.BotMessage')),
            ],
        ),
    ]
