# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot_app', '0003_botmessage_botreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmessage',
            old_name='user_id',
            new_name='sender_id',
        ),
        migrations.AddField(
            model_name='botreply',
            name='sender_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
