# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot_app', '0004_auto_20171201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='botreply',
            name='ts',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
