# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot_app', '0005_botreply_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconnection',
            old_name='user',
            new_name='admin',
        ),
    ]
