# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slack_bot_app', '0006_auto_20171201_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconnection',
            name='moderators',
            field=models.ManyToManyField(related_name='bot_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
